version: '3.9'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8090:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - 'KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092'
      - 'KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181'
    links:
      - kafka
      - zookeeper
  controller:
    build: controller
    volumes:
      - ./controller/:/action/workspace/controller
    links:
      - kafka
    restart: always
    depends_on:
      - kafka
  worker_node:
    build: worker_node
    volumes:
      - ./worker_node/:/action/workspace/worker_node
    links:
      - kafka
    depends_on:
      - kafka
      - controller
    deploy:
      mode: replicated
      replicas: 6

  web:
    build: web
    links:
      - kafka
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - kafka

  sender_answer:
    build: sender_answer
    links:
      - kafka
    restart: always
    depends_on:
      - kafka
